import dash
from dash import html, dcc, Output, Input, State
import dash_bootstrap_components as dbc

from config import (
    BG, BORDER, SHADOW, FONT_FAMILY,
    CSV_PATH, TICK_MS, REPLAY_STEP_ROWS,
    DEMO_HOME, DEMO_USER_NAME,
    GREEN, GREEN_LIGHT, RED, RED_LIGHT,
    TEXT, MUTED,
    GREEN_START, GREEN_END, PEAK_START, PEAK_END,
)

from data_service import load_data, compute_metrics
from ui_components import (
    header, metric, progress_card, streak_card, challenge_card,
    leaderboard_card, energy_bar_chart, card,
    tips_card, live_badge,
)

# Load CSV once at startup (generated by make_csv.py)
data, daily = load_data(CSV_PATH)

external_stylesheets = [
    dbc.themes.FLATLY,
    "https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800;900&display=swap",
]
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.title = "EcoEnergy Challenge (MVP)"

app.layout = html.Div(
    style={"background": BG, "minHeight": "100vh", "padding": "18px", "fontFamily": FONT_FAMILY},
    children=[
        dcc.Interval(id="tick", interval=TICK_MS, n_intervals=0),
        dcc.Store(id="replay_idx", data=0),
        dcc.Store(id="prev_rank", data=None),

        html.Div(
            style={
                "maxWidth": "1100px",
                "margin": "0 auto",
                "background": "white",
                "borderRadius": "18px",
                "overflow": "hidden",
                "border": f"1px solid {BORDER}",
                "boxShadow": SHADOW,
            },
            children=[
                header(),
                html.Div(
                    style={"padding": "16px 18px 20px 18px"},
                    children=[
                        html.Div(id="welcome_block"),
                        html.Div(style={"height": "10px"}),
                        html.Div(id="main_content"),
                    ],
                ),
            ],
        ),
    ],
)

@app.callback(
    Output("replay_idx", "data"),
    Input("tick", "n_intervals"),
    State("replay_idx", "data"),
)
def advance_replay(_, idx):
    idx = int(idx) + REPLAY_STEP_ROWS
    if idx >= len(data) - 1:
        idx = 0
    return idx

@app.callback(
    Output("welcome_block", "children"),
    Output("main_content", "children"),
    Output("prev_rank", "data"),
    Input("replay_idx", "data"),
    State("prev_rank", "data"),
)
def render(replay_idx, prev_rank):
    m = compute_metrics(data, daily, replay_idx, DEMO_HOME)
    live_time_text = m["current_ts"].strftime("%-I:%M %p")  # mac/linux


    # --- Rank movement ---
    rank = m["rank"]
    rank_delta = None
    if prev_rank is not None and rank is not None:
        rank_delta = prev_rank - rank  # positive means moved up

    if rank is None:
        rank_text = "Rank: —"
    elif rank_delta is None or rank_delta == 0:
        rank_text = f"Rank: #{rank} / {m['homes_total']} (—)"
    elif rank_delta > 0:
        rank_text = f"Rank: #{rank} / {m['homes_total']} (↑{rank_delta})"
    else:
        rank_text = f"Rank: #{rank} / {m['homes_total']} (↓{abs(rank_delta)})"

    # --- LIVE indicator blink ---
    is_live_on = (int(replay_idx) % 2 == 0)

    # --- Tip logic ---
    t = m["current_ts"].time()
    if GREEN_START <= t < GREEN_END:
        tip_title = "Green Window active"
        tip_body = "Best time to run dishwasher, laundry, or EV charging. You earn bonus points for shifting flexible loads now."
    elif PEAK_START <= t < PEAK_END:
        tip_title = "Peak Window — avoid heavy loads"
        tip_body = "Try delaying laundry/EV charging until after 9 PM. Small shifts here boost your score and reduce peak stress."
    else:
        tip_title = "Neutral hours"
        tip_body = "If you need to run a heavy device, aim for the next Green Window (10 AM–3 PM) instead of Peak (5–9 PM)."

    # --- Welcome row ---
    welcome = dbc.Row(
        [
            dbc.Col(
                html.Div(
                    [
                        html.Div(
                            f"Welcome, {DEMO_USER_NAME}!",
                            style={"fontSize": "22px", "fontWeight": 900, "color": TEXT},
                        ),
                        html.Div(live_badge(live_time_text), style={"marginTop": "6px"})
                    ],
                    style={"padding": "10px 0 0 6px"},
                ),
                md=4, xs=12,
            ),
            dbc.Col(
                metric(
                    "Today's Score:",
                    f"{m['score_pts']} pts",
                    sub=f"Live: {live_time_text}  •  Replay: Day {m['day_num']} / {m['total_days']}  •  {rank_text}"
                ),
                md=8, xs=12,
            ),
        ],
        className="g-3",
    )

    # Progress bars
    bars = dbc.Row(
        [
            dbc.Col(progress_card("Green Window Usage", m["green_kwh"], "10 AM – 3 PM", GREEN, GREEN_LIGHT, vmax=4.0), md=6, xs=12),
            dbc.Col(progress_card("Peak Window Usage", m["peak_kwh"], "5 PM – 9 PM", RED, RED_LIGHT, vmax=4.0), md=6, xs=12),
        ],
        className="g-3",
    )

    # Streak + chart
    mid = dbc.Row(
        [
            dbc.Col(streak_card(m["streak"], bonus_pct=25), md=6, xs=12),
            dbc.Col(
                card(
                    [
                        html.Div("Today: Green vs Peak", style={"fontWeight": 900, "color": TEXT, "marginBottom": "8px"}),
                        dcc.Graph(figure=energy_bar_chart(m["green_kwh"], m["peak_kwh"]), config={"displayModeBar": False}),
                    ],
                    padding="14px 14px",
                ),
                md=6, xs=12,
            ),
        ],
        className="g-3",
    )

    # Challenges
    challenges = dbc.Row(
        [
            dbc.Col(
                challenge_card(
                    "☀️", "Solar Champion",
                    "Run activity in 3 midday hours (11 AM – 2 PM)",
                    f"{m['solar_progress']} / 3 Hours Completed",
                    m["solar_progress"] / 3.0,
                    accent=GREEN,
                    completed=m["solar_completed"],
                    button="View",
                ),
                md=6, xs=12,
            ),
            dbc.Col(
                challenge_card(
                    "⛔", "Peak Dodger",
                    f"Keep peak usage under {m['peak_limit']:.1f} kWh (5 PM – 9 PM)",
                    f"{min(m['peak_kwh'], m['peak_limit']):.1f} / {m['peak_limit']:.1f} kWh",
                    min(m["peak_kwh"], m["peak_limit"]) / m["peak_limit"],
                    accent=RED,
                    completed=m["peak_completed"],
                    button=None,
                ),
                md=6, xs=12,
            ),
        ],
        className="g-3",
    )

    # Bottom: leaderboard + tips (replace "Why you earned points" with Tips)
    bottom = dbc.Row(
        [
            dbc.Col(leaderboard_card(m["leaderboard"]), md=6, xs=12),
            dbc.Col(tips_card(tip_title, tip_body), md=6, xs=12),
        ],
        className="g-3",
    )

    content = html.Div(
        [
            bars,
            html.Div(style={"height": "10px"}),
            mid,
            html.Div(style={"height": "10px"}),
            challenges,
            html.Div(style={"height": "10px"}),
            bottom,
        ]
    )

    return welcome, content, rank

if __name__ == "__main__":
    app.run(debug=True, port=8050)
